package Payload;

public class TicketingLoginBody {

	
	
	public static String CustomerBody() {
		
		return "{\r\n"
				+ "    \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "    \"officialName\": \"Bishal Rajput Dsuzuza\",\r\n"
				+ "    \"companyName\": \"Dsuzuza Groups\",\r\n"
				+ "    \"email\": \"Dsuzuza@yopmail.com\",\r\n"
				+ "    \"phoneNumber\": \"123-456-7890\",\r\n"
				+ "    \"billingAddress\": \"123 Main St.\",\r\n"
				+ "    \"status\": \"active\",\r\n"
				+ "    \"shippingAddress\": \"456 Main St.\",\r\n"
				+ "    \"address1\": \"123 Main St.\",\r\n"
				+ "    \"address2\": \"Suite 100\",\r\n"
				+ "    \"registration_no\": \"123456789\",\r\n"
				+ "    \"dun_number\": \"987654321\",\r\n"
				+ "    \"sla_unmet_condition\": \"Terms and conditions apply\",\r\n"
				+ "    \"members\": [\r\n"
				+ "        \"Alice\",\r\n"
				+ "        \"Bob\"\r\n"
				+ "    ],\r\n"
				+ "    \"notify_list\": [],\r\n"
				+ "    \"departments\": [],\r\n"
				+ "    \"logo\": \"\",\r\n"
				+ "    \"website\": \"https://example.com\",\r\n"
				+ "    \"industry\": \"Technology\",\r\n"
				+ "    \"locations\": [],\r\n"
				+ "    \"picture\": \"\",\r\n"
				+ "    \"password\": \"Test@123\",\r\n"
				+ "    \"role\": \"d393a505-df76-4ecd-9a61-a08996dde05b\",\r\n"
				+ "    \"customerLogo\": \"\",\r\n"
				+ "    \"language\": [\"hindi\",\"english\",\"marathi\"],\r\n"
				+ "    \"timezone\": \"UTC+05:30\",\r\n"
				+ "    \"paymentDetails\": {\r\n"
				+ "        \"bankName\": \"SBI\",\r\n"
				+ "        \"bankAddress\": \"Street 2 New york\",\r\n"
				+ "        \"accountNumber\": \"123456758\",\r\n"
				+ "        \"ifscCode\": \"324567\",\r\n"
				+ "        \"custId\": \"3245657\",\r\n"
				+ "        \"paymentMethod\": \"paypal\",\r\n"
				+ "        \"SWIFTBIC\": \"4345678\",\r\n"
				+ "        \"vat_number\": \"343546753435\"\r\n"
				+ "    },\r\n"
				+ "    \"skillsAndSubSkills\": [{\r\n"
				+ "        \"skill\": \"compressor repairing\",\r\n"
				+ "        \"subSkills\": [\"valve repair\",\"compressor desgining\"]\r\n"
				+ "    }],\r\n"
				+ "      \"coverage\": {\r\n"
				+ "        \"working_hours\": {\r\n"
				+ "            \"0\": null,\r\n"
				+ "            \"1\": [\r\n"
				+ "                \"10:00:00\",\r\n"
				+ "                \"20:00:00\"\r\n"
				+ "            ],\r\n"
				+ "            \"2\": [\r\n"
				+ "                \"08:00:00\",\r\n"
				+ "                \"20:00:00\"\r\n"
				+ "            ],\r\n"
				+ "            \"3\": [\r\n"
				+ "                \"08:00:00\",\r\n"
				+ "                \"20:00:00\"\r\n"
				+ "            ],\r\n"
				+ "            \"4\": [\r\n"
				+ "                \"08:00:00\",\r\n"
				+ "                \"20:00:00\"\r\n"
				+ "            ],\r\n"
				+ "            \"5\": [\r\n"
				+ "                \"08:00:00\",\r\n"
				+ "                \"20:00:00\"\r\n"
				+ "            ],\r\n"
				+ "            \"6\": null\r\n"
				+ "        },\r\n"
				+ "        \"partial_working_hours\": [\r\n"
				+ "            {\r\n"
				+ "                \"date\": \"2020-01-30\",\r\n"
				+ "                \"time\": [\r\n"
				+ "                    \"01:03:09\",\r\n"
				+ "                    \"20:04:07\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"date\": \"2020-01-27\",\r\n"
				+ "                \"time\": [\r\n"
				+ "                    \"09:08:04\",\r\n"
				+ "                    \"14:04:07\"\r\n"
				+ "                ]\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"holidays\": [\r\n"
				+ "            {\r\n"
				+ "                \"date\": [\r\n"
				+ "                    \"2019-12-28\",\r\n"
				+ "                    \"2019-12-27\"\r\n"
				+ "                ],\r\n"
				+ "                \"reason\": \"Xmas Eve\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"date\": [\r\n"
				+ "                    \"2019-11-25\"\r\n"
				+ "                ],\r\n"
				+ "                \"reason\": \"Diwali\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"alternate_working_days\": [\r\n"
				+ "            \"2019-11-25\",\r\n"
				+ "            \"2019-11-30\"\r\n"
				+ "        ]\r\n"
				+ "    }\r\n"
				+ "}";
	}
	
	
	public static String LoginBody(String emailID) {
		
		return "{\r\n"
				+ "    \"client_id\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "    \"response_type\": \"code\",\r\n"
				+ "    \"redirect_uri\": \"https://cloud-api-gateway.altorumleren.com/oauth/api/v1/test\",\r\n"
				+ "    \"grant_type\": \"pkce\",\r\n"
				+ "    \"email\": \""+emailID+"\",\r\n"
				+ "    \"password\": \"Test@123\",\r\n"
				+ "    \"code_challenge\": \"m_tVqEBmF_8-Z2fsXSf8a1aCw6ecQV724IS_fQUCc-Y\",\r\n"
				+ "    \"code_challenge_method\": \"S256\"\r\n"
				+ "}";
	}
	
	public static String AuthorizationBody(String Scope) {
		
		return "{\r\n"
				+ "    \"client_id\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                \"response_type\": \"code\",\r\n"
				+ "                \"redirect_uri\": \"https://cloud-api-gateway.altorumleren.com/oauth/api/v1/test\",\r\n"
				+ "                \"grant_type\": \"pkce\",\r\n"
				+ "                \"email\": \"gireesh.hiremath@altorumleren.com\",\r\n"
				+ "                \"password\": \"Test@123\",\r\n"
				+ "                \"code_challenge\": \"m_tVqEBmF_8-Z2fsXSf8a1aCw6ecQV724IS_fQUCc-Y\",\r\n"
				+ "                \"code_challenge_method\": \"S256\",  \r\n"
				+ "                \"client_secret\": \"{{loginResponse.loginData.client_secret}}\",\r\n"
				+ "                \"scope\": \""+Scope+"\",\r\n"
				+ "                \"role\": {\r\n"
				+ "            \"role_id\": \"06738571-de41-4d60-8454-ab7c85603192\",\r\n"
				+ "            \"name\": \"Test Role Level 2\",\r\n"
				+ "            \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "            \"customerId\": null,\r\n"
				+ "            \"tenantId\": \"b5479be0-3157-47fd-bedb-2074916be377\",\r\n"
				+ "            \"description\": \"Test description\",\r\n"
				+ "            \"level_of_access\": \"Application\",\r\n"
				+ "            \"type\": \"Team\",\r\n"
				+ "            \"dashBoardName\": \"Tenant Admin\",\r\n"
				+ "            \"accesses\": [\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"12ea3f85-e7b5-4337-bf7d-d667a85bb00e\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"94df7184-39f6-4c4a-bfa6-2df2bc666a56\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-users\",\r\n"
				+ "                        \"description\": \"Alarm users Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"14df6be2-f2db-4e14-96e4-fe8190ddfbf7\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"b9b70bc4-2bba-49f4-8152-777674cb824c\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-topics\",\r\n"
				+ "                        \"description\": \"Alarm topics Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"1729942a-7ec5-4b4e-b060-4a33d24f61ae\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"1c53c4a7-8d01-4ebd-84e2-5d3ec68041ba\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"LOC\",\r\n"
				+ "                        \"name\": \"locations-working_hours\",\r\n"
				+ "                        \"description\": \"Location Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"17e8cb6c-e7a5-45b2-ac21-6f939e07e309\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"eda626df-6c1f-4ff1-9a33-a014587638bc\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"dm-users\",\r\n"
				+ "                        \"description\": \"Device Management Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"1d36b211-d835-4fcf-8c0e-f0bc539a25ef\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"3547e039-5956-4663-b7fa-f87ef243a31c\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"proposals\",\r\n"
				+ "                        \"description\": \"proposals permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"28f1566f-0bd2-47c7-8d84-374e7cb7a700\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"4c9cebc4-d189-4af8-9cf8-9e48eb2f3bf3\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"priority\",\r\n"
				+ "                        \"description\": \"Priority permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"2c2097c6-f3a6-4a1a-8279-6f9b0a9f7e33\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"473d91e3-961e-4557-b905-cbac89b73d87\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-devices\",\r\n"
				+ "                        \"description\": \"Alarm devices Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"2c69f728-bb9e-4674-a0f2-51496af78386\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"12e1eff0-ca1d-44ee-8f95-47948831dfc3\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"settings-device\",\r\n"
				+ "                        \"description\": \"device settings\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"338c937d-10c2-4989-840c-1db5df57eb3f\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"50a25dfc-e285-42f1-a9d4-03933ee7515a\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"groups\",\r\n"
				+ "                        \"description\": \"groups\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"379eb78f-c584-424e-bf4e-149ecb789496\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"ab7538a2-5f4b-43e6-906b-2f1610896f63\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-tyres\",\r\n"
				+ "                        \"description\": \"Alarm tyres Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"3dce9d53-2edf-4502-bc97-4471b5fa42a4\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"9ef8f19e-09b3-4e9c-b1d2-09ce83ffab21\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"LOC\",\r\n"
				+ "                        \"name\": \"locations-address\",\r\n"
				+ "                        \"description\": \"Location Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"44217904-ad9b-400e-8f5a-cbaf446289a9\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"b4a49834-dab3-4de4-b41c-cbe4f844b44a\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"tenant-companyDetails\",\r\n"
				+ "                        \"description\": \"tenant management companyDetails Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"457ccc9f-1c2f-4356-b258-89c82b0d2f46\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"149789c6-f3ed-4fbb-8fe6-ed3e67d163f6\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-settings\",\r\n"
				+ "                        \"description\": \"Alarm settings Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"4b819000-480c-4691-b14b-4c4ad9fb3edf\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"95ee6f17-199c-4166-999e-ef1be5f79600\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"dm-assets\",\r\n"
				+ "                        \"description\": \"Assets Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"4cc6501e-e9df-4f84-8ccd-8d27f401f752\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"cb003dc0-67f9-4ffb-88fc-41bae74d7cb9\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"tenant-systemAdmin\",\r\n"
				+ "                        \"description\": \"tenant management systemAdmin Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"4db10ce9-63c1-4ae7-a6ad-3041b0044827\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"e4db33a8-3314-4b0d-93f3-11ac11f0020e\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"PROD\",\r\n"
				+ "                        \"name\": \"productmanagement-products\",\r\n"
				+ "                        \"description\": \"list of Products\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"4f2db3af-2866-4a68-b0d3-64440f1dbc52\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"db7e5a7e-5050-40c4-b901-4c76329b0c76\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"LOC\",\r\n"
				+ "                        \"name\": \"locations-location_types\",\r\n"
				+ "                        \"description\": \"Location Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"555597c0-4c47-439a-b850-5cadd37f0124\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"ee61cb24-ed1a-498a-a4f6-08be0762c8cf\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"tags\",\r\n"
				+ "                        \"description\": \"Tags permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"591caac6-89b1-40d4-9085-56f4a6d67890\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"f901764b-8d2a-40d5-b359-00c96f736899\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"NOTIFY\",\r\n"
				+ "                        \"name\": \"settings-notification\",\r\n"
				+ "                        \"description\": \" Permission for settings in notification\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"5a210485-2825-4021-9a43-d3888f1b2079\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"a937eaa1-229a-4d5f-a351-bf462676ad48\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"settings\",\r\n"
				+ "                        \"description\": \"settings page\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"5abc82a7-98ae-4259-8646-7414875c4891\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"976bf17f-a876-4fcb-a636-db39ecb37156\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"dm-devices\",\r\n"
				+ "                        \"description\": \"Device Management Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"5dfc2187-e485-4cf3-9885-7667649792a8\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"c50ee4b0-fe5f-4ea3-801b-69145ddbc4b3\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-customers\",\r\n"
				+ "                        \"description\": \"CRM Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"6012e9e6-27f1-4f6a-becd-f1fbd965acc4\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"e5d57d1a-f37f-4521-a9c4-de15819dbd47\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"knowledgebase\",\r\n"
				+ "                        \"description\": \"knowledgebase\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"6408c21e-e020-489a-88f3-6a54f81574de\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"8331473b-cf51-4fb0-afa7-03dc3ba134dd\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"dm-gateways\",\r\n"
				+ "                        \"description\": \"Device Management Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"65b71b58-3423-444c-8a28-f6840fcbc08c\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"da63d9e3-73d5-4ad3-888d-85c2c4e30c35\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-groups\",\r\n"
				+ "                        \"description\": \"CRM groups permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"6e5700bc-5447-48f8-80b6-5490e169ff64\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"a1f7c829-6455-49b7-b12c-cf5fc1f5b483\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"departments\",\r\n"
				+ "                        \"description\": \"departments\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"6fbbd9c5-17aa-4fae-a1bb-8e475fc30f26\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"51bc0196-860b-4399-a76b-907b6ef88c17\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-mapping\",\r\n"
				+ "                        \"description\": \"Alarm mapping Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"75f32977-cd74-4ec6-b9cc-15cdd907a344\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"e495d7f5-fb22-4d54-8643-2b4615170dcb\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"subscriptions\",\r\n"
				+ "                        \"description\": \"subscriptions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"771834d0-af82-42e2-af09-f9520f54d3c4\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"012586bf-b9f3-4927-9280-debf6b2c1af0\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"packages\",\r\n"
				+ "                        \"description\": \"packages\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"87862c2c-f4c6-4da4-ba1a-806dcfbaf897\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"e742c581-d653-4f34-a50b-ca24cf19a4e6\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"settings-tpms\",\r\n"
				+ "                        \"description\": \"tpms settings permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"8bd57be8-a939-4bd9-9bd4-d9fd2ee0f76b\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"6e13dfd4-f0d8-4f15-a90d-c2bd531a14bc\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"ALM\",\r\n"
				+ "                        \"name\": \"alarms-trains\",\r\n"
				+ "                        \"description\": \"Alarm trains Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"8d343c63-49e7-483b-bae7-f35ecf349622\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"2dcdedc2-f49a-4a72-8bfa-19e8f6ee3115\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"tenant-users\",\r\n"
				+ "                        \"description\": \"tenant management users Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"8d9e503f-5d89-4161-ab22-174bd3883d7a\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"4ea56841-b962-4dde-b237-cdbcd4c6fa95\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"payments\",\r\n"
				+ "                        \"description\": \"payments\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"8f6f9042-ecc2-47b0-b78e-586b34af0d12\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"8d1ace40-85b3-460b-9a51-de58337a1821\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"HELPDESK\",\r\n"
				+ "                        \"name\": \"helpdesk-setting\",\r\n"
				+ "                        \"description\": \" Permission for helpdesk setting\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"91179e4f-8c7c-4ccc-97d8-d66509ac9ff1\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"f09cb336-0a44-4c34-970c-a5ac6c3c8715\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-roles\",\r\n"
				+ "                        \"description\": \"crm roles permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"948fe339-4ec4-427d-bca0-50489e14e6dc\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"e073a800-bd4a-4cfd-ae51-d48329b17f82\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"dm-tags\",\r\n"
				+ "                        \"description\": \"Device Management Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"9d3304a7-e798-4652-b977-7641540cd2c8\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"4c78bc78-5ee9-4f2f-9098-3ef1ca9795fd\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"sla\",\r\n"
				+ "                        \"description\": \"Service Level Agreement permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"9df3a6f1-bcc8-46e9-a277-e59a47ff14ff\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"926b8421-e253-4f77-9e72-e0ab0bc37ae4\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-tenantpersons\",\r\n"
				+ "                        \"description\": \"Crm management tenant persons Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"9fee1dcb-4e46-4a1a-8ce9-83d77aaf11f4\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"42210cb3-c087-4435-ab5b-4fc6d1f3fca4\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"INVENTORY\",\r\n"
				+ "                        \"name\": \"im-products\",\r\n"
				+ "                        \"description\": \"Products of Inventory Microservice permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"a0f723f6-9d53-423e-b5eb-2c7654042fc5\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"5cf6d851-89d4-4ab8-8997-07784880a9f6\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"contracts\",\r\n"
				+ "                        \"description\": \"Contracts permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"a5218371-6ef6-475e-a432-fc0d16784cb7\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"b76c58c5-9cd2-42a5-a646-9786a2d9bdbb\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"HD\",\r\n"
				+ "                        \"name\": \"helpdesk\",\r\n"
				+ "                        \"description\": \"helpdesk management permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"aa993e08-3d7b-4693-9266-8152ecf556a2\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"3b7a1165-10db-4214-b0aa-8781f58b9e9c\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"tenant-roles\",\r\n"
				+ "                        \"description\": \"tenant management roles Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"b3598e90-0073-4aeb-8db2-52d84552cba9\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"9b091324-ddb1-4222-9835-82fbe48037da\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"scope-of-work\",\r\n"
				+ "                        \"description\": \"Scope of work permissions\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"b91c04eb-2d37-4f04-a854-cd44d11444cd\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"f249341c-1a0d-41f5-a34b-df6a44519109\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"tickets\",\r\n"
				+ "                        \"description\": \"tickets\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"ba921737-b11e-42ef-a3a4-b17506f19937\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"08396274-12da-4e8c-a41f-d87526acc4ef\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"SUB\",\r\n"
				+ "                        \"name\": \"subscription-helpdesk\",\r\n"
				+ "                        \"description\": \" Permission for helpdesk subscription\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"c82b5df3-7304-45a2-ae94-bf71821e630d\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"1bf8e34e-ade3-4464-93a6-6336307dfba9\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-teams\",\r\n"
				+ "                        \"description\": \"CRM teams permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"cf7d726b-052e-48a5-9339-ac091a9e166f\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"view\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"d9849023-da3a-44e8-aa93-34f712fc5136\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-tenants\",\r\n"
				+ "                        \"description\": \"CRM Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"d124e608-b5db-41b5-9d84-010f85665f54\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"0821396e-0bbb-4d6c-83eb-850c19c77dbc\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"HELPDESK\",\r\n"
				+ "                        \"name\": \"helpdesk-tickets\",\r\n"
				+ "                        \"description\": \"Tickets in helpdesk\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"d2ed512f-3715-4284-8cca-0e4ad03ac3f7\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"6f154db5-f599-42aa-b8c1-47d06a878ed4\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"HELPDESK\",\r\n"
				+ "                        \"name\": \"helpdesk-cases\",\r\n"
				+ "                        \"description\": \"Cases in helpdesk\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"d5c1bbbb-0c64-46d7-9e4d-301d84841ea1\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"4b196b61-e853-4b16-9ddc-51e1b2e6022b\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"devices\",\r\n"
				+ "                        \"description\": \"device\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"d6e1f10b-61a5-4a73-b447-daf754c18745\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"ee47a456-35eb-4076-9b1e-a3d57925cf89\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"teams\",\r\n"
				+ "                        \"description\": \"teams\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"dc429ba9-1ec0-45f2-9ed4-8980e715b7b0\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"c9535936-10bd-46ba-ae0e-467c1be5dc55\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"TICKETING\",\r\n"
				+ "                        \"name\": \"accounts\",\r\n"
				+ "                        \"description\": \"accounts\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"e285dadd-96f8-47b2-8318-7f9bbd67d208\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"8f86cd96-33c0-4ac2-ba89-2b11c6f33cce\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"LOC\",\r\n"
				+ "                        \"name\": \"locations-locations\",\r\n"
				+ "                        \"description\": \"Location Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"e4796b9d-62e0-49d4-b176-7cca09084ad8\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"9cfd2715-d622-459c-b831-11f4b9c14625\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"DM\",\r\n"
				+ "                        \"name\": \"dm-cronJobSettings\",\r\n"
				+ "                        \"description\": \"cronJob Settings Permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"ed4b2298-2574-4329-ac62-a638b9827b52\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"5bd36c84-1ee4-4e12-85a7-3b43561bc762\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"PROD\",\r\n"
				+ "                        \"name\": \"productmanagement\",\r\n"
				+ "                        \"description\": \"product management permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"eeacf208-104a-4833-88e5-1904b2d73a09\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"facb55c4-a145-406f-b9da-37923960bb21\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-departments\",\r\n"
				+ "                        \"description\": \"CRM department permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"faa43835-db79-430b-aa69-465d2fbcc227\",\r\n"
				+ "                    \"grants\": [\r\n"
				+ "                        \"*\"\r\n"
				+ "                    ],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"a6db5184-a7a8-4721-ba54-2a0366988b4a\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"CRM\",\r\n"
				+ "                        \"name\": \"crm-users\",\r\n"
				+ "                        \"description\": \"crm users permission\"\r\n"
				+ "                    }\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"access_id\": \"fbc2a362-ad1e-49a0-859d-bb7cd8dde4ae\",\r\n"
				+ "                    \"grants\": [],\r\n"
				+ "                    \"permission\": {\r\n"
				+ "                        \"permission_id\": \"8aba433c-5f8b-4a30-9c84-cbf03f2fcfc1\",\r\n"
				+ "                        \"clientId\": \"b3caf465-235a-4d15-a99d-ffbff5f24552\",\r\n"
				+ "                        \"scope\": \"PROD\",\r\n"
				+ "                        \"name\": \"productmanagement-installedproducts\",\r\n"
				+ "                        \"description\": \"list of Installed Products\"\r\n"
				+ "                    }\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        }\r\n"
				+ "}";
	}

}
